#include <cstdint>
#include <cstddef>
#include <limine.h>
#include "sqlos/runtime/sqlos_runtime.hpp"

// Set the base revision to 6, this is recommended as this is the latest
// base revision described by the Limine boot protocol specification.
// See specification for further info.

namespace {

__attribute__((used, section(".limine_requests")))
volatile std::uint64_t limine_base_revision[] = LIMINE_BASE_REVISION(6);

}

// The Limine requests can be placed anywhere, but it is important that
// the compiler does not optimise them away, so, usually, they should
// be made volatile or equivalent, _and_ they should be accessed at least
// once or marked as used with the "used" attribute as done here.

// Finally, define the start and end markers for the Limine requests.
// These can also be moved anywhere, to any .cpp file, as seen fit.

namespace {

__attribute__((used, section(".limine_requests_start")))
volatile std::uint64_t limine_requests_start_marker[] = LIMINE_REQUESTS_START_MARKER;

__attribute__((used, section(".limine_requests_end")))
volatile std::uint64_t limine_requests_end_marker[] = LIMINE_REQUESTS_END_MARKER;

}

// Halt and catch fire function, defined below.
namespace {

void hcf();

}

// The following stubs are required by the Itanium C++ ABI (the one we use,
// regardless of the "Itanium" nomenclature).
// Like the memory functions in memory.cpp, these stubs can be moved to a different .cpp file,
// but should not be removed, unless you know what you are doing.
extern "C" {
    int __cxa_atexit(void (*)(void *), void *, void *) { return 0; }
    void __cxa_pure_virtual() { hcf(); }
    void __cxa_deleted_virtual() { hcf(); }
    void *__dso_handle;
    // Not thread safe: replace before statics can be initialised concurrently.
    int __cxa_guard_acquire(std::uint64_t *guard) { return *reinterpret_cast<std::uint8_t *>(guard) == 0; }
    void __cxa_guard_release(std::uint64_t *guard) { *reinterpret_cast<std::uint8_t *>(guard) = 1; }
}

// Extern declarations for global constructors array.
extern void (*__init_array[])();
extern void (*__init_array_end[])();

// Halt and catch fire function.
namespace {

void hcf() {
    for (;;) {
#if defined (__x86_64__)
        asm ("hlt");
#elif defined (__aarch64__) || defined (__riscv)
        asm ("wfi");
#elif defined (__loongarch64)
        asm ("idle 0");
#endif
    }
}

// --- SSE ---------------------------------------------------------------------
//
// src/sql/program.cpp (generated by sqlos from src/sql/program.sql) is the
// only translation unit built with SSE allowed: the SQL-OS value model has
// IEEE doubles, and the SysV x86-64 ABI returns doubles in xmm registers,
// which the kernel's -mno-sse -mno-80387 flags forbid everywhere else (see
// the GNUmakefile). Turn the hardware on before anything from that
// translation unit — or any global constructor — runs.

void enable_sse() {
    std::uint64_t cr0;
    std::uint64_t cr4;
    asm volatile("mov %%cr0, %0" : "=r"(cr0));
    cr0 &= ~((std::uint64_t{1} << 2) | (std::uint64_t{1} << 3));  // CR0.EM = 0, CR0.TS = 0
    cr0 |= (std::uint64_t{1} << 1);                                // CR0.MP = 1
    asm volatile("mov %0, %%cr0" : : "r"(cr0) : "memory");
    asm volatile("mov %%cr4, %0" : "=r"(cr4));
    cr4 |= (std::uint64_t{1} << 10);                               // CR4.OSFXSR: SSE usable
    cr4 |= (std::uint64_t{1} << 9);                                // CR4.OSXMMEXCPT: SSE exceptions
    asm volatile("mov %0, %%cr4" : : "r"(cr4) : "memory");
}

// --- debug port --------------------------------------------------------------
//
// QEMU captures everything written to port 0xE9 with:
//   -device isa-debugcon,chardev=<id> -chardev file,id=<id>,path=e9.log
// Bochs reads it directly; real serial-level hardware often maps it too.

void e9_putc(char c) {
    sqlos::outb(0xE9, static_cast<sqlos::u8>(c));
}

// --- buffered table output ---------------------------------------------------
//
// Rows are held until their result set ends (the next header, or the end of
// the program) so every column can be sized to its widest entry — header
// name or cell — which makes the `|` bars line up; cells are centered
// inside their column with spaces. A result set longer than kTableRows is
// flushed early: the continuation keeps its own consistent widths.

void put_bytes(const char *p, sqlos::u32 n) {
    for (sqlos::u32 k = 0; k < n; ++k) e9_putc(p[k]);
}

// A printable view of one cell: text already points into the program's
// arena; everything else formats into buf (>= 21 chars for any i64).
struct CellView {
    const char *p;
    sqlos::u32 n;
};

CellView cell_view(const sqlos::Value &v, char *buf) {
    using K = sqlos::Kind;
    switch (v.kind) {
        case K::Int:
            return {buf, sqlos::fmt_i64(v.as_int, buf)};
        case K::Text:
            return {v.as_text.p, v.as_text.len};
        case K::Bool:
            buf[0] = v.as_bool ? 't' : 'f';
            return {buf, 1};
        case K::Null:
            buf[0] = '-';
            return {buf, 1};
        case K::Real:
            buf[0] = '?';
            return {buf, 1};
    }
    buf[0] = '?';  // unreachable: Kind has no other values
    return {buf, 1};
}

// Print a value centered in `width` columns (extra space to the right).
void put_centered(const char *p, sqlos::u32 n, sqlos::u32 width) {
    if (n < width) {
        const sqlos::u32 left = (width - n) / 2;
        const sqlos::u32 right = width - n - left;
        for (sqlos::u32 k = 0; k < left; ++k) e9_putc(' ');
        put_bytes(p, n);
        for (sqlos::u32 k = 0; k < right; ++k) e9_putc(' ');
    } else {
        put_bytes(p, n);  // cannot happen: widths cover every stored cell
    }
}

constexpr sqlos::u32 kTableCols = SQLOS_MAX_COLS;
constexpr sqlos::u32 kTableRows = 32;

struct Table {
    bool active;
    const char *const *names;
    sqlos::u32 ncols;
    sqlos::u32 nrows;
    sqlos::u32 width[kTableCols];
    sqlos::Value rows[kTableRows][kTableCols];
};

Table table = {};

// Prints the buffered result set: header (names centered per column), an
// underline spanning the full width, then the rows. Keeps the header, so a
// forced mid-set flush only restarts the row buffer.
void flush_table() {
    if (!table.active) return;
    char buf[24];
    for (sqlos::u32 i = 0; i < table.ncols; ++i) {
        sqlos::u32 w = 0;
        while (table.names[i][w] != '\0') ++w;  // the header name
        for (sqlos::u32 r = 0; r < table.nrows; ++r) {
            const CellView cv = cell_view(table.rows[r][i], buf);
            if (cv.n > w) w = cv.n;
        }
        table.width[i] = w;
    }
    for (sqlos::u32 i = 0; i < table.ncols; ++i) {
        if (i != 0) e9_putc('|');
        sqlos::u32 n = 0;
        while (table.names[i][n] != '\0') ++n;
        put_centered(table.names[i], n, table.width[i]);
    }
    e9_putc('\n');
    sqlos::u32 total = table.ncols - 1;
    for (sqlos::u32 i = 0; i < table.ncols; ++i) total += table.width[i];
    for (sqlos::u32 k = 0; k < total; ++k) e9_putc('-');
    e9_putc('\n');
    for (sqlos::u32 r = 0; r < table.nrows; ++r) {
        for (sqlos::u32 i = 0; i < table.ncols; ++i) {
            if (i != 0) e9_putc('|');
            const CellView cv = cell_view(table.rows[r][i], buf);
            put_centered(cv.p, cv.n, table.width[i]);
        }
        e9_putc('\n');
    }
    table.nrows = 0;
}

// sqlos::HeaderFn: a result set's column names — ends the previous one.
void print_header(void *, const char *const *cols, sqlos::u32 ncols) {
    flush_table();
    table.active = ncols != 0 && ncols <= kTableCols;
    table.names = cols;
    table.ncols = ncols;
    table.nrows = 0;
}

// sqlos::SinkFn: buffer the row (or print it plainly when no header was
// announced for it).
void print_row(void *, const sqlos::Row *row) {
    if (!table.active) {
        char buf[24];
        for (sqlos::u32 i = 0; i < row->count; ++i) {
            if (i != 0) e9_putc('|');
            const CellView cv = cell_view(row->cells[i], buf);
            put_bytes(cv.p, cv.n);
        }
        e9_putc('\n');
        return;
    }
    if (table.nrows >= kTableRows) flush_table();
    const sqlos::u32 n = row->count < table.ncols ? row->count : table.ncols;
    for (sqlos::u32 i = 0; i < n; ++i) table.rows[table.nrows][i] = row->cells[i];
    for (sqlos::u32 i = n; i < table.ncols; ++i) {
        table.rows[table.nrows][i] = sqlos::Value::null();
    }
    ++table.nrows;
}

}

// The following will be our kernel's entry point.
// If renaming kmain() to something else, make sure to change the
// linker script accordingly.
extern "C" void kmain() {
    // Ensure the bootloader actually understands our base revision (see spec).
    if (LIMINE_BASE_REVISION_SUPPORTED(limine_base_revision) == false) {
        hcf();
    }

    // SSE before any constructor or generated SQL code can execute.
    enable_sse();

    // Call global constructors.
    for (std::size_t i = 0; &__init_array[i] != __init_array_end; i++) {
        __init_array[i]();
    }

    // Run the program that `sqlos --emit` produced from src/sql/program.sql.
    // Its `INSERT INTO io_8_write (port, value)` rows do real outb to 0xE9;
    // each result set's column names go to print_header, and every row it
    // SELECTs is handed to print_row.
    sqlos_program(print_row, print_header, nullptr);

    // The final result set ends with the program.
    flush_table();

    // We're done, just hang...
    hcf();
}
