#include <cstdint>
#include <cstddef>
#include <limine.h>
#include "sqlos/runtime/sqlos_runtime.hpp"

// Set the base revision to 6, this is recommended as this is the latest
// base revision described by the Limine boot protocol specification.
// See specification for further info.

namespace {

__attribute__((used, section(".limine_requests")))
volatile std::uint64_t limine_base_revision[] = LIMINE_BASE_REVISION(6);

}

// The Limine requests can be placed anywhere, but it is important that
// the compiler does not optimise them away, so, usually, they should
// be made volatile or equivalent, _and_ they should be accessed at least
// once or marked as used with the "used" attribute as done here.

// Finally, define the start and end markers for the Limine requests.
// These can also be moved anywhere, to any .cpp file, as seen fit.

namespace {

__attribute__((used, section(".limine_requests_start")))
volatile std::uint64_t limine_requests_start_marker[] = LIMINE_REQUESTS_START_MARKER;

__attribute__((used, section(".limine_requests_end")))
volatile std::uint64_t limine_requests_end_marker[] = LIMINE_REQUESTS_END_MARKER;

}

// --- Limine boot requests ----------------------------------------------------
//
// The bootloader fills the responses below; init_boot_tables() copies them
// into the SQL boot tables (memory_map, boot_info) before the program runs.
// Volatile so the compiler actually reads what the bootloader wrote.

namespace {

__attribute__((used, section(".limine_requests")))
volatile struct limine_bootloader_info_request bootloader_info_request = {
    .id = LIMINE_BOOTLOADER_INFO_REQUEST_ID,
    .revision = 0,
    .response = nullptr,
};

__attribute__((used, section(".limine_requests")))
volatile struct limine_executable_cmdline_request cmdline_request = {
    .id = LIMINE_EXECUTABLE_CMDLINE_REQUEST_ID,
    .revision = 0,
    .response = nullptr,
};

__attribute__((used, section(".limine_requests")))
volatile struct limine_firmware_type_request firmware_type_request = {
    .id = LIMINE_FIRMWARE_TYPE_REQUEST_ID,
    .revision = 0,
    .response = nullptr,
};

__attribute__((used, section(".limine_requests")))
volatile struct limine_hhdm_request hhdm_request = {
    .id = LIMINE_HHDM_REQUEST_ID,
    .revision = 0,
    .response = nullptr,
};

__attribute__((used, section(".limine_requests")))
volatile struct limine_executable_address_request executable_address_request = {
    .id = LIMINE_EXECUTABLE_ADDRESS_REQUEST_ID,
    .revision = 0,
    .response = nullptr,
};

__attribute__((used, section(".limine_requests")))
volatile struct limine_memmap_request memmap_request = {
    .id = LIMINE_MEMMAP_REQUEST_ID,
    .revision = 0,
    .response = nullptr,
};

__attribute__((used, section(".limine_requests")))
volatile struct limine_framebuffer_request framebuffer_request = {
    .id = LIMINE_FRAMEBUFFER_REQUEST_ID,
    .revision = 0,
    .response = nullptr,
};

__attribute__((used, section(".limine_requests")))
volatile struct limine_module_request module_request = {
    .id = LIMINE_MODULE_REQUEST_ID,
    .revision = 0,
    .response = nullptr,
    .internal_module_count = 0,
    .internal_modules = nullptr,
};

__attribute__((used, section(".limine_requests")))
volatile struct limine_date_at_boot_request date_at_boot_request = {
    .id = LIMINE_DATE_AT_BOOT_REQUEST_ID,
    .revision = 0,
    .response = nullptr,
};

}

// Halt and catch fire function, defined below.
namespace {

void hcf();

}

// The following stubs are required by the Itanium C++ ABI (the one we use,
// regardless of the "Itanium" nomenclature).
// Like the memory functions in memory.cpp, these stubs can be moved to a different .cpp file,
// but should not be removed, unless you know what you are doing.
extern "C" {
    int __cxa_atexit(void (*)(void *), void *, void *) { return 0; }
    void __cxa_pure_virtual() { hcf(); }
    void __cxa_deleted_virtual() { hcf(); }
    void *__dso_handle;
    // Not thread safe: replace before statics can be initialised concurrently.
    int __cxa_guard_acquire(std::uint64_t *guard) { return *reinterpret_cast<std::uint8_t *>(guard) == 0; }
    void __cxa_guard_release(std::uint64_t *guard) { *reinterpret_cast<std::uint8_t *>(guard) = 1; }
}

// Extern declarations for global constructors array.
extern void (*__init_array[])();
extern void (*__init_array_end[])();

// Halt and catch fire function.
namespace {

void hcf() {
    for (;;) {
#if defined (__x86_64__)
        asm ("hlt");
#elif defined (__aarch64__) || defined (__riscv)
        asm ("wfi");
#elif defined (__loongarch64)
        asm ("idle 0");
#endif
    }
}

// --- SSE ---------------------------------------------------------------------
//
// src/sql/program.cpp (generated by sqlos from src/sql/program.sql) is the
// only translation unit built with SSE allowed: the SQL-OS value model has
// IEEE doubles, and the SysV x86-64 ABI returns doubles in xmm registers,
// which the kernel's -mno-sse -mno-80387 flags forbid everywhere else (see
// the GNUmakefile). Turn the hardware on before anything from that
// translation unit — or any global constructor — runs.

void enable_sse() {
    std::uint64_t cr0;
    std::uint64_t cr4;
    asm volatile("mov %%cr0, %0" : "=r"(cr0));
    cr0 &= ~((std::uint64_t{1} << 2) | (std::uint64_t{1} << 3));  // CR0.EM = 0, CR0.TS = 0
    cr0 |= (std::uint64_t{1} << 1);                                // CR0.MP = 1
    asm volatile("mov %0, %%cr0" : : "r"(cr0) : "memory");
    asm volatile("mov %%cr4, %0" : "=r"(cr4));
    cr4 |= (std::uint64_t{1} << 10);                               // CR4.OSFXSR: SSE usable
    cr4 |= (std::uint64_t{1} << 9);                                // CR4.OSXMMEXCPT: SSE exceptions
    asm volatile("mov %0, %%cr4" : : "r"(cr4) : "memory");
}

// --- debug port --------------------------------------------------------------
//
// QEMU captures everything written to port 0xE9 with:
//   -device isa-debugcon,chardev=<id> -chardev file,id=<id>,path=e9.log
// Bochs reads it directly; real serial-level hardware often maps it too.

void e9_putc(char c) {
    sqlos::outb(0xE9, static_cast<sqlos::u8>(c));
}

// --- buffered table output ---------------------------------------------------
//
// Rows are held until their result set ends (the next header, or the end of
// the program) so every column can be sized to its widest entry — header
// name or cell — which makes the `|` bars line up; cells are centered
// inside their column with spaces. A result set longer than kTableRows is
// flushed early: the continuation keeps its own consistent widths.

void put_bytes(const char *p, sqlos::u32 n) {
    for (sqlos::u32 k = 0; k < n; ++k) e9_putc(p[k]);
}

// A printable view of one cell: text already points into the program's
// arena; everything else formats into buf (>= 21 chars for any i64).
struct CellView {
    const char *p;
    sqlos::u32 n;
};

CellView cell_view(const sqlos::Value &v, char *buf) {
    using K = sqlos::Kind;
    switch (v.kind) {
        case K::Int:
            return {buf, sqlos::fmt_i64(v.as_int, buf)};
        case K::Text:
            return {v.as_text.p, v.as_text.len};
        case K::Bool:
            buf[0] = v.as_bool ? 't' : 'f';
            return {buf, 1};
        case K::Null:
            buf[0] = '-';
            return {buf, 1};
        case K::Real:
            buf[0] = '?';
            return {buf, 1};
    }
    buf[0] = '?';  // unreachable: Kind has no other values
    return {buf, 1};
}

// Print a value centered in `width` columns (extra space to the right).
void put_centered(const char *p, sqlos::u32 n, sqlos::u32 width) {
    if (n < width) {
        const sqlos::u32 left = (width - n) / 2;
        const sqlos::u32 right = width - n - left;
        for (sqlos::u32 k = 0; k < left; ++k) e9_putc(' ');
        put_bytes(p, n);
        for (sqlos::u32 k = 0; k < right; ++k) e9_putc(' ');
    } else {
        put_bytes(p, n);  // cannot happen: widths cover every stored cell
    }
}

constexpr sqlos::u32 kTableCols = SQLOS_MAX_COLS;
constexpr sqlos::u32 kTableRows = 32;

struct Table {
    bool active;
    const char *const *names;
    sqlos::u32 ncols;
    sqlos::u32 nrows;
    sqlos::u32 width[kTableCols];
    sqlos::Value rows[kTableRows][kTableCols];
};

Table table = {};

// Prints the buffered result set: header (names centered per column), an
// underline spanning the full width, then the rows. Keeps the header, so a
// forced mid-set flush only restarts the row buffer.
void flush_table() {
    if (!table.active) return;
    char buf[24];
    for (sqlos::u32 i = 0; i < table.ncols; ++i) {
        sqlos::u32 w = 0;
        while (table.names[i][w] != '\0') ++w;  // the header name
        for (sqlos::u32 r = 0; r < table.nrows; ++r) {
            const CellView cv = cell_view(table.rows[r][i], buf);
            if (cv.n > w) w = cv.n;
        }
        table.width[i] = w + 2;  // one space of air per side, so even the
                                 // longest value keeps a left pad
    }
    for (sqlos::u32 i = 0; i < table.ncols; ++i) {
        if (i != 0) { e9_putc(' '); e9_putc('|'); e9_putc(' '); }
        sqlos::u32 n = 0;
        while (table.names[i][n] != '\0') ++n;
        put_centered(table.names[i], n, table.width[i]);
    }
    e9_putc('\n');
    sqlos::u32 total = 3 * (table.ncols - 1);
    for (sqlos::u32 i = 0; i < table.ncols; ++i) total += table.width[i];
    for (sqlos::u32 k = 0; k < total; ++k) e9_putc('-');
    e9_putc('\n');
    for (sqlos::u32 r = 0; r < table.nrows; ++r) {
        for (sqlos::u32 i = 0; i < table.ncols; ++i) {
            if (i != 0) { e9_putc(' '); e9_putc('|'); e9_putc(' '); }
            const CellView cv = cell_view(table.rows[r][i], buf);
            put_centered(cv.p, cv.n, table.width[i]);
        }
        e9_putc('\n');
    }
    table.nrows = 0;
}

// sqlos::HeaderFn: a result set's column names — ends the previous one.
void print_header(void *, const char *const *cols, sqlos::u32 ncols) {
    flush_table();
    table.active = ncols != 0 && ncols <= kTableCols;
    table.names = cols;
    table.ncols = ncols;
    table.nrows = 0;
}

// sqlos::SinkFn: buffer the row (or print it plainly when no header was
// announced for it). Columns are always separated by " | ".
void print_row(void *, const sqlos::Row *row) {
    if (!table.active) {
        char buf[24];
        for (sqlos::u32 i = 0; i < row->count; ++i) {
            if (i != 0) { e9_putc(' '); e9_putc('|'); e9_putc(' '); }
            const CellView cv = cell_view(row->cells[i], buf);
            put_bytes(cv.p, cv.n);
        }
        e9_putc('\n');
        return;
    }
    if (table.nrows >= kTableRows) flush_table();
    const sqlos::u32 n = row->count < table.ncols ? row->count : table.ncols;
    for (sqlos::u32 i = 0; i < n; ++i) table.rows[table.nrows][i] = row->cells[i];
    for (sqlos::u32 i = n; i < table.ncols; ++i) {
        table.rows[table.nrows][i] = sqlos::Value::null();
    }
    ++table.nrows;
}

}

// --- boot tables -------------------------------------------------------------
//
// The Limine responses above become the SQL `memory_map` (one row per
// entry) and `boot_info` (one row) tables. Both are read-only to SQL.
// Address columns are TEXT hex because upper-half HHDM/kernel addresses
// do not fit SQL's signed integers; lengths, dimensions and counts stay
// INT so they can be computed with. Values keep pointers, so every text
// they hold is either a literal, bootloader-owned memory, or one of the
// static buffers below.

namespace {

const char* map_type_name(std::uint64_t type) {
    switch (type) {
        case LIMINE_MEMMAP_USABLE: return "usable";
        case LIMINE_MEMMAP_RESERVED: return "reserved";
        case LIMINE_MEMMAP_ACPI_RECLAIMABLE: return "acpi_reclaimable";
        case LIMINE_MEMMAP_ACPI_NVS: return "acpi_nvs";
        case LIMINE_MEMMAP_BAD_MEMORY: return "bad";
        case LIMINE_MEMMAP_BOOTLOADER_RECLAIMABLE: return "bootloader";
        case LIMINE_MEMMAP_EXECUTABLE_AND_MODULES: return "kernel";
        case LIMINE_MEMMAP_FRAMEBUFFER: return "framebuffer";
        case LIMINE_MEMMAP_RESERVED_MAPPED: return "reserved_mapped";
        default: return "unknown";
    }
}

const char* firmware_name(std::uint64_t type) {
    switch (type) {
        case LIMINE_FIRMWARE_TYPE_X86BIOS: return "x86bios";
        case LIMINE_FIRMWARE_TYPE_EFI32: return "efi32";
        case LIMINE_FIRMWARE_TYPE_EFI64: return "efi64";
        case LIMINE_FIRMWARE_TYPE_SBI: return "sbi";
        default: return "unknown";
    }
}

sqlos::u32 cstr_len(const char* s) {
    sqlos::u32 n = 0;
    while (s[n] != '\0') ++n;
    return n;
}

// "0x" + trimmed lowercase hex (leading zeros dropped, "0" kept for zero).
// out needs 19 bytes; returns the length written.
sqlos::u32 fmt_hex(sqlos::u64 v, char* out) {
    char tmp[16];
    sqlos::u32 n = 0;
    for (int shift = 60; shift >= 0; shift -= 4) {
        const sqlos::u32 d = static_cast<sqlos::u32>((v >> shift) & 0xF);
        if (n == 0 && d == 0 && shift != 0) continue;
        tmp[n++] = static_cast<char>(d < 10 ? '0' + d : 'a' + (d - 10));
    }
    out[0] = '0';
    out[1] = 'x';
    for (sqlos::u32 i = 0; i < n; ++i) out[2 + i] = tmp[i];
    return 2 + n;
}

// Hex TEXT cells point into these; they must outlive init_boot_tables().
char g_hex_hhdm[24];
char g_hex_phys[24];
char g_hex_virt[24];
char g_hex_fb[24];

sqlos::Value hex_cell(char* buf, sqlos::u64 v) {
    return sqlos::Value::t(buf, fmt_hex(v, buf));
}

void init_boot_tables() {
    // memory_map: one row per Limine entry, capped by SQLOS_MEMMAP_CAP.
    if (memmap_request.response != nullptr) {
        const struct limine_memmap_response* resp = memmap_request.response;
        for (std::uint64_t i = 0; i < resp->entry_count; ++i) {
            if (sqlos::g_memory_map.count >= SQLOS_MEMMAP_CAP) break;
            const struct limine_memmap_entry* e = resp->entries[i];
            if (e == nullptr) continue;
            const sqlos::u32 row = sqlos::g_memory_map.count;
            sqlos::g_memory_map.c0[row] =
                sqlos::Value::i(static_cast<sqlos::i64>(e->base));
            sqlos::g_memory_map.c1[row] =
                sqlos::Value::i(static_cast<sqlos::i64>(e->length));
            const char* type = map_type_name(e->type);
            sqlos::g_memory_map.c2[row] = sqlos::Value::t(type, cstr_len(type));
            ++sqlos::g_memory_map.count;
        }
    }

    // boot_info: always one row; an absent response arrives as NULL.
    sqlos::BootInfoStore& b = sqlos::g_boot_info;
    b.count = 1;
    if (hhdm_request.response != nullptr) {
        b.c0[0] = hex_cell(g_hex_hhdm, hhdm_request.response->offset);
    }
    if (executable_address_request.response != nullptr) {
        b.c1[0] = hex_cell(g_hex_phys,
                           executable_address_request.response->physical_base);
        b.c2[0] = hex_cell(g_hex_virt,
                           executable_address_request.response->virtual_base);
    }
    if (bootloader_info_request.response != nullptr) {
        const char* name = bootloader_info_request.response->name;
        if (name != nullptr) b.c3[0] = sqlos::Value::t(name, cstr_len(name));
        const char* ver = bootloader_info_request.response->version;
        if (ver != nullptr) b.c4[0] = sqlos::Value::t(ver, cstr_len(ver));
    }
    if (cmdline_request.response != nullptr &&
        cmdline_request.response->cmdline != nullptr) {
        const char* cl = cmdline_request.response->cmdline;
        b.c5[0] = sqlos::Value::t(cl, cstr_len(cl));
    }
    if (firmware_type_request.response != nullptr) {
        const char* fw = firmware_name(firmware_type_request.response->firmware_type);
        b.c6[0] = sqlos::Value::t(fw, cstr_len(fw));
    }
    if (framebuffer_request.response != nullptr &&
        framebuffer_request.response->framebuffer_count > 0 &&
        framebuffer_request.response->framebuffers[0] != nullptr) {
        const struct limine_framebuffer* fb =
            framebuffer_request.response->framebuffers[0];
        b.c7[0] = hex_cell(g_hex_fb, reinterpret_cast<sqlos::u64>(fb->address));
        b.c8[0] = sqlos::Value::i(static_cast<sqlos::i64>(fb->width));
        b.c9[0] = sqlos::Value::i(static_cast<sqlos::i64>(fb->height));
        b.c10[0] = sqlos::Value::i(static_cast<sqlos::i64>(fb->bpp));
    }
    if (module_request.response != nullptr) {
        b.c11[0] = sqlos::Value::i(
            static_cast<sqlos::i64>(module_request.response->module_count));
    }
    if (date_at_boot_request.response != nullptr) {
        b.c12[0] = sqlos::Value::i(
            static_cast<sqlos::i64>(date_at_boot_request.response->timestamp));
    }
}

}

// The following will be our kernel's entry point.
// If renaming kmain() to something else, make sure to change the
// linker script accordingly.
extern "C" void kmain() {
    // Ensure the bootloader actually understands our base revision (see spec).
    if (LIMINE_BASE_REVISION_SUPPORTED(limine_base_revision) == false) {
        hcf();
    }

    // SSE before any constructor or generated SQL code can execute.
    enable_sse();

    // Call global constructors.
    for (std::size_t i = 0; &__init_array[i] != __init_array_end; i++) {
        __init_array[i]();
    }

    // Fill the SQL boot tables (memory_map, boot_info) from the Limine
    // responses, then run the program that `sqlos --emit` produced from
    // src/sql/program.sql. Its `INSERT INTO io_8_write (port, value)` rows
    // do real outb to 0xE9; each result set's column names go to
    // print_header, and every row it SELECTs is handed to print_row.
    init_boot_tables();
    sqlos_program(print_row, print_header, nullptr);

    // The final result set ends with the program.
    flush_table();

    // We're done, just hang...
    hcf();
}
